on:
  push:
    branches:
      - main

env:
  tag_name: v1

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git -c user.name="$(git log -n 1 --pretty=format:%an)" -c user.email="$(git log -n 1 --pretty=format:%ae)" tag ${{ env.tag_name }}
          git push origin ${{ env.tag_name }}
